### ISSUE TITLE
sbt plugin not published on bintray

### ISSUE THREAD

**Issue by fabriziofortino** [mediative/sangria-codegen#8]
Can the `sbt-sangria-codegen` be published on https://dl.bintray.com/mediative/maven/com/mediative/ ?

**Comment by jonas** [comment]
It's currently published to https://dl.bintray.com/mediative/sbt-plugins/com.mediative/sbt-sangria-codegen/ so can be used with

```
resolvers += Resolver.bintrayRepo("mediative", "sbt-plugins")
```

Once version 0.1.0 is released the plan is to get it included in the sbt plugins repo so no custom resolver settings are needed.

**Comment by fabriziofortino** [comment]
To make it work I had to use the bintray ivy repo

`resolvers += Resolver.bintrayIvyRepo("mediative", "sbt-plugins")`

Thanks! 🙇
